#services:
#  pi-sparkfi:
#    image: cp0x/pi-sparkfi-interface:0.1.7
#    container_name: pi-sparkfi-interface
#    restart: always
#    ports:
#      - "3002:4000"
#    tty: true

services:
  pi-sparkfi:
    image: cp0x/pi-sparkfi-interface:latest
    container_name: pi-sparkfi-interface
    ports:
      - "3002:3000"
    tty: true
  pi-sparkfi-backend:
    image: cp0x/pi-sparkfi-interface:latest
    command: sh -c "cd app && pnpm run prod"
    ports:
      - "3004:4000"
    container_name: pi-sparkfi-interface-backend
    tty: true
